#ifndef CONFIG_H_
#define CONFIG_H_

//SERIAL SETTINGS
#define BAUD 115200

//CHOICE OF MCU BOARDS TO DRIVE ROBOT. BY DEFAULT: 0 (MEGA2560)    单片机板驱动机器人的选择。默认情况下：0（MEGA2560）
#define BOARD_CHOICE WEMOSD1R32
     //CHOICES: 
     //  MEGA2560
     //  UNO
     //  WEMOSD1R32
     
     //..DO NOT CHANGE BELOW BOARD VALUES..//
     #define MEGA2560    0 //ARDUINO MEGA2560 & RAMPS 1.4
     #define UNO         1 //ARDUINO UNO & CNC SHIELD
     #define WEMOSD1R32  2 //ESP32 - WEMOS D1 R32 & CNC SHIELD
     //PLEASE SEE & ADJUST ESP32 PARAMETERS IN [config_esp32.h]

//ROBOT ARM LENGTH
//#define SHANK_LENGTH 140.0
#define LOW_SHANK_LENGTH 120.0 //大臂长度
#define HIGH_SHANK_LENGTH 120.0   //小臂长度

#define END_EFFECTOR_OFFSET 30.0 // LENGTH FROM UPPER SHANK BEARING TO MIDPOINT OF END EFFECTOR IN MM  从上柄轴承到末端执行器中点的长度（MM） 54

//INITIAL INTERPOLATION SETTINGS
//  INITIAL_XYZ FORMS VERTICAL LOWER ARM & HORIZONTAL UPPER ARM IN 90 DEGREES
#define INITIAL_X 0.0 // CARTESIAN COORDINATE X   笛卡尔坐标系 我们不需要 rotate
#define INITIAL_Y (HIGH_SHANK_LENGTH+END_EFFECTOR_OFFSET) // CARTESIAN COORDINATE Y 小臂
#define INITIAL_Z LOW_SHANK_LENGTH // CARTESIAN COORDINATE Z 大臂

#define INITIAL_E0 0.0 // RAIL STEPPER ENDSTOP POSITION  轨道步进器末端停止位置

//  CALIBRATE HOME STEPS TO REACH DESIRED INITIAL_XYZ POSITIONS   校准起始步骤以达到所需的初始XYZ位置
#define X_HOME_STEPS 1020 //765 //860 // STEPS FROM X_ENDSTOP TO INITIAL_XYZ FOR UPPER ARM 上臂从限位到INITIAL_XYZ的步长
#define Y_HOME_STEPS 1900 //1940 // STEPS FROM Y_ENDSTOP TO INITIAL_XYZ FOR LOWER ARM
#define Z_HOME_STEPS 3640 // STEPS FROM Z_ENDSTOP TO INITIAL_XYZ FOR ROTATION CENTER
#define E0_HOME_STEPS 500 // STEPS FROM E0_ENDSTOP TO INITIAL_E0

//HOMING SETTINGS: 归位设置
#define HOME_X_STEPPER true // "true" IF ENDSTOP IS INSTALLED 如果安装了ENDSTOP，则为“true”
#define HOME_Y_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_Z_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_E0_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_ON_BOOT false // "true" IF HOMING REQUIRED AFTER POWER ON 如果通电后需要复位，则为“true”
#define HOME_DWELL 800 // INCREASE TO SLOW DOWN HOMING SPEED 增加以减慢归航速度

//STEPPER SETTINGS: 步进器设置
#define MICROSTEPS 16 // MICROSTEPPING CONFIGURATION ON RAMPS1.4  斜坡上的微步进配置1.4
#define STEPS_PER_REV 200 // NEMA17 STEPS PER REVOLUTION 每转NEMA17步
#define INVERSE_X_STEPPER true // CHANGE IF STEPPER MOVES OTHER WAY 如果步进器向其他方向移动，则进行更改
#define INVERSE_Y_STEPPER false // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_Z_STEPPER true // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_E0_STEPPER false // CHANGE IF STEPPER MOVES OTHER WAY

//RAIL SETTINGS: 轨道设置
#define RAIL false // E0 STEPPER USED AS RAIL. SET TO 'false' IF ROBOT ARM IS STATIONARY.  E0步进器用作导轨。如果机器人手臂静止，则设置为“false”。
#define STEPS_PER_MM_RAIL 160  // STEPS PER MM FOR RAIL MOTOR 轨道电机每毫米步数
        //FORMULA: STEPS_PER_REV * MICROSTEPS / MOTOR_GEAR_TEETH / 2 公式：步数PER_REV*微步数/电机GEAR_TEETH
#define RAIL_LENGTH 400.0 // MAX LENGTH OF RAIL IN MM 钢轨的最大长度（MM）

//ENDSTOP SETTINGS:
#define X_MIN_INPUT 0 // OUTPUT VALUE WHEN SWITCH ACTIVATED - NO: 0, NC: 1 开关激活时的输出值
#define Y_MIN_INPUT 0 // OUTPUT VALUE WHEN SWITCH ACTIVATED - NO: 0, NC: 1
#define Z_MIN_INPUT 0 // OUTPUT VALUE WHEN SWITCH ACTIVATED - NO: 0, NC: 1
#define E0_MIN_INPUT 0 // OUTPUT VALUE WHEN SWITCH ACTIVATED - NO: 0, NC: 1

//GEAR RATIO SETTINGS 传动比设置
#define MOTOR_GEAR_TEETH 20.0 // 20.0 FOR 20SFFACTORY BELT VERSION   9.0 FOR FTOBLER GEAR VERSION 20.0适用于20SFFACTORY皮带版本
#define MAIN_GEAR_TEETH 90.0 // 90.0 FOR 20SFFACTORY BELT VERSION   32.0 FOR FTOBLER GEAR VERSION

//EQUIPMENT SETTINGS 设备设置
#define LASER false // 12V LASER CONNECTED TO LASER_PIN 12V激光器连接到LASER_PIN
#define PUMP false // 12V AIR PUMP CONNECTED TO PUMP_PIN 12V空气泵连接到泵_PIN
#define FAN_DELAY 120 // FAN ON IN SECONDS 风扇在几秒钟内打开

//GRIPPER SETTINGS 夹持器设置
#define GRIPPER 1 //GRIPPER MOTOR IN USE
     // 0: 28BYJ-48 MICRO STEPPER MOTOR (WORKS ON BOARD_CHOICE MEGA2560 ONLY) 28BYJ-48微型步进电机（仅适用于板上选择MEGA2560）
     // 1: 9G SERVO OR MG996 SERVO EQUIVALENT 9G伺服或MG996伺服等效
     
     //..DO NOT CHANGE BELOW MOTOR DEFINE VALUES..//
     #define BYJ 0
     #define SERVO 1

//28BYJ GRIPPER SETTINGS 28BYJ夹具设置
#define BYJ_GRIP_STEPS 1200 //FTOBLER: 1200
//SERVO GRIPPER SETTINGS
#define SERVO_GRIP_DEGREE 90.0
#define SERVO_UNGRIP_DEGREE 0.0

//COMMAND QUEUE SETTINGS 命令队列设置
#define QUEUE_SIZE 15

//PRINT REPLY SETTING 打印回复设置
#define PRINT_REPLY false // "true" TO PRINT MSG AFTER ONE COMMAND IS PROCESSED 处理一个命令后打印消息
#define PRINT_REPLY_MSG "ok" // MSG SENT FOR USER'S POST PROCESSING WITH OTHER SOFTWARE 发送消息供用户使用其他软件进行后期处理

//DEFAULT SPEED PROFILE SETTING  默认速度配置文件设置
#define SPEED_PROFILE 2 // OPTIONS BELOW
//0: FLAT SPEED CURVE (CONSTANT SPEED PER MOVEMENT, SUITABLE FOR REALTIME CONTROL SOFTWARE)
//1: ARCTAN APPROX (SLIGHT BELL CURVE ACCELERATION & DECELERATION)
//2: COSIN APPROX (TOTAL BELL CURVE ACCEL FROM 0 & DECEL TO 0, SUITABLE FOR PRESET COMMAND MOVEMENTS)

//LOG SETTINGS
#define LOG_LEVEL 2
//0: ERROR
//1: INFO
//2: DEBUG

//MOVE LIMIT PARAMETERS 移动限制参数
#define Z_MIN -140.0 //MINIMUM Z HEIGHT OF TOOLHEAD TOUCHING GROUND
#define Z_MAX (LOW_SHANK_LENGTH+30.0) //SHANK_LENGTH ADDING ARBITUARY NUMBER FOR Z_MAX      zmax的SHANK_LENGTH加仲裁数
#define SHANKS_MIN_ANGLE_COS 0.791436948 
#define SHANKS_MAX_ANGLE_COS -0.774944489 
#define R_MIN (sqrt((sq(LOW_SHANK_LENGTH) + sq(HIGH_SHANK_LENGTH)) - (2*LOW_SHANK_LENGTH*HIGH_SHANK_LENGTH*SHANKS_MIN_ANGLE_COS) ))
#define R_MAX (sqrt((sq(LOW_SHANK_LENGTH) + sq(HIGH_SHANK_LENGTH)) - (2*LOW_SHANK_LENGTH*HIGH_SHANK_LENGTH*SHANKS_MAX_ANGLE_COS) ))

#endif
